
TRANSLATIONS = {
    'EN': {
        'sidebar_title': "Navigation",
        'select_language': "Select Language",
        'welcome_title': "Economics & Data Science Portfolio",
        'welcome_subtitle': "Intersection of Economic Theory and Advanced Analytics",
        'intro_text': "This portfolio demonstrates advanced **Microeconomics** and **Macroeconomics** concepts visualized through **Data Science** techniques. Explore the modules in the sidebar.",
        'micro': "Microeconomics Strategy",
        'macro': "Macroeconomics & Policy",
        'metrics': "Econometrics & Real Data",
        'supply_demand': "Supply & Demand",
        'supply_demand_desc': "Simulate demand and supply forces.",
        'market_struct': "Market Structures",
        'market_struct_desc': "Perfect Comp, Monopoly, Oligopoly (Kinked Demand).",
        'prod_opt': "Production Optimization",
        'prod_opt_desc': "Managerial Cost Minimization (Isoquant/Isocost).",
        'policy': "Public Policy",
        'policy_desc': "Taxes, Subsidies, DWL.",
        'game_theory': "Game Theory Simulator",
        'game_theory_desc': "Prisoner's Dilemma & Price Wars.",
        'investment': "Investment Locator",
        'investment_desc': "Multi-Criteria Decision Analysis (MCDA).",
        'growth': "Growth Optimizer",
        'growth_desc': "Solow Model & Policy AI Optimizer.",
        'equil': "Macro Equilibrium",
        'equil_desc': "IS-LM & AD-AS Models.",
        'wage': "Wage (UMR) Calculator",
        'wage_desc': "Min Wage & Purchasing Power Parity (KHL).",
        'forecasting': "Time Series Forecasting",
        'forecasting_desc': "Holt-Winters GDP Prediction.",
        'real_data': "Real-World Dashboard",
        'real_data_desc': "Live World Bank Data (GDP, Inflation).",
        'lab': "Econometrics Lab",
        'lab_desc': "Regression Analysis & Synthetic Data."
    },
    'ID': {
        'sidebar_title': "Navigasi",
        'select_language': "Pilih Bahasa",
        'welcome_title': "Portofolio Ekonomi & Data Science",
        'welcome_subtitle': "Titik Temu Teori Ekonomi dan Analisis Data Canggih",
        'intro_text': "Portofolio ini mendemonstrasikan konsep **Ekonomi Mikro** dan **Makro** tingkat lanjut yang divisualisasikan melalui teknik **Data Science**. Jelajahi modul di sidebar.",
        'micro': "Strategi Ekonomi Mikro",
        'macro': "Ekonomi Makro & Kebijakan",
        'metrics': "Ekonometrika & Data Riil",
        'supply_demand': "Permintaan & Penawaran",
        'supply_demand_desc': "Simulasi kekuatan pasar.",
        'market_struct': "Struktur Pasar",
        'market_struct_desc': "Persaingan Sempurna, Monopoli, Oligopoli (Kurva Patah).",
        'prod_opt': "Optimasi Produksi",
        'prod_opt_desc': "Minimisasi Biaya Manajerial (Isokuan/Isocost).",
        'policy': "Kebijakan Publik",
        'policy_desc': "Pajak, Subsidi, DWL.",
        'game_theory': "Simulasi Teori Permainan",
        'game_theory_desc': "Dilema Tahanan & Perang Harga.",
        'investment': "Pencari Lokasi Investasi",
        'investment_desc': "Analisis Keputusan Multi-Kriteria (MCDA).",
        'growth': "Optimasi Pertumbuhan",
        'growth_desc': "Model Solow & AI Optimizer Kebijakan.",
        'equil': "Ekuilibrium Makro",
        'equil_desc': "Model IS-LM & AD-AS.",
        'wage': "Kalkulator Upah (UMR)",
        'wage_desc': "Upah Minimum & Daya Beli (KHL).",
        'forecasting': "Peramalan Runtut Waktu",
        'forecasting_desc': "Prediksi PDB Holt-Winters.",
        'real_data': "Dashboard Data Riil",
        'real_data_desc': "Data Live Bank Dunia (PDB, Inflasi).",
        'lab': "Lab Ekonometrika",
        'lab_desc': "Analisis Regresi & Data Sintetis."
    }
}

def get_text(key, lang='ID'):
    return TRANSLATIONS.get(lang, TRANSLATIONS['ID']).get(key, key)
