from fpdf import FPDF
import datetime

def create_header(pdf, title):
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, title, 0, 1, 'C')
    pdf.ln(10)

def generate_certificate_pdf(student_name, course_name, score):
    """Generates a PDF certificate and returns the bytes."""
    pdf = FPDF()
    pdf.add_page()
    
    # Border
    pdf.set_line_width(3)
    pdf.rect(10, 10, 190, 277)
    
    # Header
    pdf.image('https://cdn-icons-png.flaticon.com/512/3135/3135715.png', x=95, y=20, w=20) # Mock Logo
    pdf.ln(25)
    
    pdf.set_font("Arial", 'B', 28)
    pdf.set_text_color(22, 101, 52) # Green-800
    pdf.cell(0, 20, "CERTIFICATE OF COMPLETION", 0, 1, 'C')
    pdf.ln(10)
    
    pdf.set_font("Arial", '', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "This certifies that", 0, 1, 'C')
    
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(30, 41, 59) # Slate-800
    pdf.cell(0, 20, student_name, 0, 1, 'C')
    
    pdf.set_line_width(1)
    pdf.line(60, 105, 150, 105)
    pdf.ln(10)
    
    pdf.set_font("Arial", '', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Has successfully completed the course", 0, 1, 'C')
    
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(37, 99, 235) # Blue-600
    pdf.cell(0, 15, course_name, 0, 1, 'C')
    pdf.ln(15)
    
    pdf.set_font("Arial", 'I', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"Score Achieved: {score:.0f}%", 0, 1, 'C')
    pdf.cell(0, 10, f"Date: {datetime.date.today().strftime('%B %d, %Y')}", 0, 1, 'C')
    
    pdf.ln(30)
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, "Verified by UTel University Curriculum Engine", 0, 1, 'C')
    pdf.cell(0, 5, "AgriSensa API Integration", 0, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1')

def generate_syllabus_pdf(course_data):
    """Generates a PDF syllabus and returns the bytes."""
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 20)
    pdf.cell(0, 10, f"{course_data['id']} - {course_data['name']}", 0, 1, 'C')
    pdf.set_font("Arial", 'I', 12)
    pdf.cell(0, 10, f"Credits: {course_data['credits']} | Difficulty: {course_data['difficulty']}", 0, 1, 'C')
    pdf.line(10, 30, 200, 30)
    pdf.ln(15)
    
    # Description
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Course Description", 0, 1)
    pdf.set_font("Arial", '', 12)
    pdf.multi_cell(0, 8, course_data['description'])
    pdf.ln(10)
    
    # Topics
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Key Topics", 0, 1)
    pdf.set_font("Arial", '', 12)
    
    for topic in course_data.get('topics', []):
        pdf.cell(10, 8, "- ", 0, 0)
        pdf.multi_cell(0, 8, topic)
        
    pdf.ln(10)
    
    # Resources
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Learning Resources", 0, 1)
    pdf.set_font("Arial", '', 12)
    
    for res in course_data.get('resources', []):
        type_icon = "[VIDEO]" if res['type'] == 'youtube' else "[LINK]"
        pdf.cell(0, 8, f"{type_icon} {res['title']}", 0, 1)
        pdf.set_font("Arial", 'I', 10)
        pdf.cell(0, 6, f"   Access: {res['url']}", 0, 1)
        pdf.set_font("Arial", '', 12)
        pdf.ln(2)
        
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by UTel Academic Portal", 0, 1, 'C')
    
    return pdf.output(dest='S').encode('latin-1')
