[theme]
primaryColor = "#6366f1"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
