"""
Feed Database Service
Comprehensive database of 100+ feed ingredients with complete nutritional profiles
"""

# ==========================================
# 📊 FEED INGREDIENT DATABASE
# ==========================================

FEED_DATABASE = {
    # ========== ENERGY FEEDS - GRAINS ==========
    "Jagung Kuning": {
        "category": "Energy Feed - Grain",
        "dry_matter": 88.0,
        "crude_protein": 9.0,
        "crude_fiber": 2.5,
        "ether_extract": 4.0,
        "ash": 1.5,
        "nfe": 71.0,
        "tdn": 80.0,
        "de_ruminant": 3.54,
        "me_ruminant": 2.90,
        "ne_lactation": 2.00,
        "ne_maintenance": 2.18,
        "ne_gain": 1.42,
        "de_poultry": 3.40,
        "me_poultry": 3.20,
        "lysine": 0.25,
        "methionine": 0.18,
        "methionine_cystine": 0.36,
        "threonine": 0.30,
        "tryptophan": 0.07,
        "calcium": 0.02,
        "phosphorus": 0.28,
        "price_per_kg": 4500
    },
    "Jagung Giling": {
        "category": "Energy Feed - Grain",
        "dry_matter": 87.0,
        "crude_protein": 8.5,
        "crude_fiber": 2.8,
        "ether_extract": 3.8,
        "ash": 1.4,
        "nfe": 70.5,
        "tdn": 79.0,
        "de_ruminant": 3.48,
        "me_ruminant": 2.85,
        "ne_lactation": 1.96,
        "ne_maintenance": 2.14,
        "ne_gain": 1.39,
        "de_poultry": 3.35,
        "me_poultry": 3.15,
        "lysine": 0.24,
        "methionine": 0.17,
        "methionine_cystine": 0.35,
        "threonine": 0.29,
        "tryptophan": 0.06,
        "calcium": 0.02,
        "phosphorus": 0.27,
        "price_per_kg": 4300
    },
    "Sorgum": {
        "category": "Energy Feed - Grain",
        "dry_matter": 89.0,
        "crude_protein": 10.0,
        "crude_fiber": 2.2,
        "ether_extract": 3.5,
        "ash": 1.8,
        "nfe": 71.5,
        "tdn": 78.0,
        "de_ruminant": 3.44,
        "me_ruminant": 2.82,
        "ne_lactation": 1.94,
        "ne_maintenance": 2.11,
        "ne_gain": 1.37,
        "de_poultry": 3.30,
        "me_poultry": 3.10,
        "lysine": 0.22,
        "methionine": 0.16,
        "methionine_cystine": 0.32,
        "threonine": 0.28,
        "tryptophan": 0.10,
        "calcium": 0.03,
        "phosphorus": 0.30,
        "price_per_kg": 4000
    },
    "Gandum": {
        "category": "Energy Feed - Grain",
        "dry_matter": 89.0,
        "crude_protein": 13.0,
        "crude_fiber": 2.8,
        "ether_extract": 2.0,
        "ash": 1.8,
        "nfe": 69.4,
        "tdn": 77.0,
        "de_ruminant": 3.39,
        "me_ruminant": 2.78,
        "ne_lactation": 1.91,
        "ne_maintenance": 2.08,
        "ne_gain": 1.35,
        "de_poultry": 3.25,
        "me_poultry": 3.05,
        "lysine": 0.35,
        "methionine": 0.20,
        "methionine_cystine": 0.42,
        "threonine": 0.32,
        "tryptophan": 0.14,
        "calcium": 0.05,
        "phosphorus": 0.38,
        "price_per_kg": 6000
    },
    "Beras Pecah": {
        "category": "Energy Feed - Grain",
        "dry_matter": 88.0,
        "crude_protein": 7.5,
        "crude_fiber": 0.5,
        "ether_extract": 0.8,
        "ash": 0.6,
        "nfe": 78.6,
        "tdn": 82.0,
        "de_ruminant": 3.61,
        "me_ruminant": 2.96,
        "ne_lactation": 2.04,
        "ne_maintenance": 2.22,
        "ne_gain": 1.45,
        "de_poultry": 3.45,
        "me_poultry": 3.25,
        "lysine": 0.38,
        "methionine": 0.16,
        "methionine_cystine": 0.30,
        "threonine": 0.28,
        "tryptophan": 0.10,
        "calcium": 0.02,
        "phosphorus": 0.15,
        "price_per_kg": 8000
    },
    
    # ========== ENERGY FEEDS - BY-PRODUCTS ==========
    "Dedak Padi": {
        "category": "Energy Feed - By-product",
        "dry_matter": 90.0,
        "crude_protein": 13.0,
        "crude_fiber": 11.0,
        "ether_extract": 13.0,
        "ash": 10.0,
        "nfe": 43.0,
        "tdn": 68.0,
        "de_ruminant": 2.99,
        "me_ruminant": 2.45,
        "ne_lactation": 1.68,
        "ne_maintenance": 1.84,
        "ne_gain": 1.19,
        "de_poultry": 2.85,
        "me_poultry": 2.65,
        "lysine": 0.55,
        "methionine": 0.20,
        "methionine_cystine": 0.42,
        "threonine": 0.45,
        "tryptophan": 0.15,
        "calcium": 0.07,
        "phosphorus": 1.50,
        "price_per_kg": 3500
    },
    "Pollard": {
        "category": "Energy Feed - By-product",
        "dry_matter": 89.0,
        "crude_protein": 16.0,
        "crude_fiber": 9.0,
        "ether_extract": 4.5,
        "ash": 5.0,
        "nfe": 54.5,
        "tdn": 72.0,
        "de_ruminant": 3.17,
        "me_ruminant": 2.60,
        "ne_lactation": 1.79,
        "ne_maintenance": 1.95,
        "ne_gain": 1.27,
        "de_poultry": 3.00,
        "me_poultry": 2.80,
        "lysine": 0.60,
        "methionine": 0.22,
        "methionine_cystine": 0.45,
        "threonine": 0.48,
        "tryptophan": 0.18,
        "calcium": 0.14,
        "phosphorus": 1.10,
        "price_per_kg": 4200
    },
    "Molasses (Tetes Tebu)": {
        "category": "Energy Feed - By-product",
        "dry_matter": 75.0,
        "crude_protein": 4.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.2,
        "ash": 10.0,
        "nfe": 60.8,
        "tdn": 60.0,
        "de_ruminant": 2.64,
        "me_ruminant": 2.17,
        "ne_lactation": 1.49,
        "ne_maintenance": 1.62,
        "ne_gain": 1.05,
        "de_poultry": 2.50,
        "me_poultry": 2.30,
        "lysine": 0.10,
        "methionine": 0.05,
        "methionine_cystine": 0.10,
        "threonine": 0.08,
        "tryptophan": 0.02,
        "calcium": 0.90,
        "phosphorus": 0.10,
        "price_per_kg": 2500
    },
    "Onggok (Gaplek)": {
        "category": "Energy Feed - By-product",
        "dry_matter": 88.0,
        "crude_protein": 2.5,
        "crude_fiber": 15.0,
        "ether_extract": 0.5,
        "ash": 3.0,
        "nfe": 67.0,
        "tdn": 65.0,
        "de_ruminant": 2.86,
        "me_ruminant": 2.35,
        "ne_lactation": 1.61,
        "ne_maintenance": 1.76,
        "ne_gain": 1.14,
        "de_poultry": 2.70,
        "me_poultry": 2.50,
        "lysine": 0.08,
        "methionine": 0.04,
        "methionine_cystine": 0.08,
        "threonine": 0.06,
        "tryptophan": 0.02,
        "calcium": 0.20,
        "phosphorus": 0.15,
        "price_per_kg": 2000
    },
    
    # ========== ENERGY FEEDS - FATS & OILS ==========
    "Minyak Kelapa Sawit": {
        "category": "Energy Feed - Fat/Oil",
        "dry_matter": 99.0,
        "crude_protein": 0.0,
        "crude_fiber": 0.0,
        "ether_extract": 99.0,
        "ash": 0.0,
        "nfe": 0.0,
        "tdn": 200.0,
        "de_ruminant": 8.80,
        "me_ruminant": 7.22,
        "ne_lactation": 4.97,
        "ne_maintenance": 5.41,
        "ne_gain": 3.52,
        "de_poultry": 8.50,
        "me_poultry": 8.00,
        "lysine": 0.0,
        "methionine": 0.0,
        "methionine_cystine": 0.0,
        "threonine": 0.0,
        "tryptophan": 0.0,
        "calcium": 0.0,
        "phosphorus": 0.0,
        "price_per_kg": 15000
    },
    
    # ========== PROTEIN FEEDS - PLANT ORIGIN ==========
    "Bungkil Kedelai": {
        "category": "Protein Feed - Plant",
        "dry_matter": 89.0,
        "crude_protein": 48.0,
        "crude_fiber": 6.0,
        "ether_extract": 1.5,
        "ash": 6.5,
        "nfe": 27.0,
        "tdn": 78.0,
        "de_ruminant": 3.43,
        "me_ruminant": 2.82,
        "ne_lactation": 1.94,
        "ne_maintenance": 2.11,
        "ne_gain": 1.37,
        "de_poultry": 3.30,
        "me_poultry": 3.10,
        "lysine": 3.00,
        "methionine": 0.68,
        "methionine_cystine": 1.35,
        "threonine": 1.90,
        "tryptophan": 0.65,
        "calcium": 0.30,
        "phosphorus": 0.65,
        "price_per_kg": 7500
    },
    "Bungkil Kelapa": {
        "category": "Protein Feed - Plant",
        "dry_matter": 91.0,
        "crude_protein": 21.0,
        "crude_fiber": 12.0,
        "ether_extract": 8.0,
        "ash": 6.0,
        "nfe": 44.0,
        "tdn": 70.0,
        "de_ruminant": 3.08,
        "me_ruminant": 2.53,
        "ne_lactation": 1.74,
        "ne_maintenance": 1.89,
        "ne_gain": 1.23,
        "de_poultry": 2.95,
        "me_poultry": 2.75,
        "lysine": 0.65,
        "methionine": 0.35,
        "methionine_cystine": 0.70,
        "threonine": 0.75,
        "tryptophan": 0.22,
        "calcium": 0.20,
        "phosphorus": 0.60,
        "price_per_kg": 4500
    },
    "Bungkil Kacang Tanah": {
        "category": "Protein Feed - Plant",
        "dry_matter": 92.0,
        "crude_protein": 48.0,
        "crude_fiber": 11.0,
        "ether_extract": 6.0,
        "ash": 5.0,
        "nfe": 22.0,
        "tdn": 75.0,
        "de_ruminant": 3.30,
        "me_ruminant": 2.71,
        "ne_lactation": 1.86,
        "ne_maintenance": 2.03,
        "ne_gain": 1.32,
        "de_poultry": 3.15,
        "me_poultry": 2.95,
        "lysine": 1.80,
        "methionine": 0.50,
        "methionine_cystine": 1.10,
        "threonine": 1.40,
        "tryptophan": 0.50,
        "calcium": 0.25,
        "phosphorus": 0.70,
        "price_per_kg": 6500
    },
    "CGM (Corn Gluten Meal)": {
        "category": "Protein Feed - Plant",
        "dry_matter": 90.0,
        "crude_protein": 60.0,
        "crude_fiber": 2.5,
        "ether_extract": 3.0,
        "ash": 2.0,
        "nfe": 22.5,
        "tdn": 82.0,
        "de_ruminant": 3.61,
        "me_ruminant": 2.96,
        "ne_lactation": 2.04,
        "ne_maintenance": 2.22,
        "ne_gain": 1.45,
        "de_poultry": 3.45,
        "me_poultry": 3.25,
        "lysine": 1.20,
        "methionine": 1.80,
        "methionine_cystine": 2.50,
        "threonine": 2.00,
        "tryptophan": 0.30,
        "calcium": 0.10,
        "phosphorus": 0.50,
        "price_per_kg": 12000
    },
    
    # ========== PROTEIN FEEDS - ANIMAL ORIGIN ==========
    "Tepung Ikan": {
        "category": "Protein Feed - Animal",
        "dry_matter": 92.0,
        "crude_protein": 65.0,
        "crude_fiber": 0.0,
        "ether_extract": 10.0,
        "ash": 15.0,
        "nfe": 2.0,
        "tdn": 75.0,
        "de_ruminant": 3.30,
        "me_ruminant": 2.71,
        "ne_lactation": 1.86,
        "ne_maintenance": 2.03,
        "ne_gain": 1.32,
        "de_poultry": 3.15,
        "me_poultry": 2.95,
        "lysine": 5.00,
        "methionine": 1.90,
        "methionine_cystine": 2.60,
        "threonine": 2.80,
        "tryptophan": 0.70,
        "calcium": 5.50,
        "phosphorus": 3.00,
        "price_per_kg": 18000
    },
    "Tepung Tulang": {
        "category": "Protein Feed - Animal",
        "dry_matter": 94.0,
        "crude_protein": 50.0,
        "crude_fiber": 0.0,
        "ether_extract": 10.0,
        "ash": 30.0,
        "nfe": 4.0,
        "tdn": 65.0,
        "de_ruminant": 2.86,
        "me_ruminant": 2.35,
        "ne_lactation": 1.61,
        "ne_maintenance": 1.76,
        "ne_gain": 1.14,
        "de_poultry": 2.70,
        "me_poultry": 2.50,
        "lysine": 3.50,
        "methionine": 1.20,
        "methionine_cystine": 1.80,
        "threonine": 2.00,
        "tryptophan": 0.40,
        "calcium": 10.00,
        "phosphorus": 5.00,
        "price_per_kg": 15000
    },
    "MBM (Meat and Bone Meal)": {
        "category": "Protein Feed - Animal",
        "dry_matter": 93.0,
        "crude_protein": 50.0,
        "crude_fiber": 2.0,
        "ether_extract": 12.0,
        "ash": 25.0,
        "nfe": 4.0,
        "tdn": 68.0,
        "de_ruminant": 2.99,
        "me_ruminant": 2.45,
        "ne_lactation": 1.68,
        "ne_maintenance": 1.84,
        "ne_gain": 1.19,
        "de_poultry": 2.85,
        "me_poultry": 2.65,
        "lysine": 2.80,
        "methionine": 0.70,
        "methionine_cystine": 1.20,
        "threonine": 1.80,
        "tryptophan": 0.30,
        "calcium": 8.00,
        "phosphorus": 4.00,
        "price_per_kg": 12000
    },
    "Tepung Darah": {
        "category": "Protein Feed - Animal",
        "dry_matter": 92.0,
        "crude_protein": 85.0,
        "crude_fiber": 0.0,
        "ether_extract": 1.0,
        "ash": 4.0,
        "nfe": 2.0,
        "tdn": 70.0,
        "de_ruminant": 3.08,
        "me_ruminant": 2.53,
        "ne_lactation": 1.74,
        "ne_maintenance": 1.89,
        "ne_gain": 1.23,
        "de_poultry": 2.95,
        "me_poultry": 2.75,
        "lysine": 7.50,
        "methionine": 1.00,
        "methionine_cystine": 1.50,
        "threonine": 4.00,
        "tryptophan": 1.20,
        "calcium": 0.30,
        "phosphorus": 0.30,
        "price_per_kg": 20000
    },
    "Tepung Bulu": {
        "category": "Protein Feed - Animal",
        "dry_matter": 93.0,
        "crude_protein": 85.0,
        "crude_fiber": 0.0,
        "ether_extract": 5.0,
        "ash": 3.0,
        "nfe": 0.0,
        "tdn": 65.0,
        "de_ruminant": 2.86,
        "me_ruminant": 2.35,
        "ne_lactation": 1.61,
        "ne_maintenance": 1.76,
        "ne_gain": 1.14,
        "de_poultry": 2.70,
        "me_poultry": 2.50,
        "lysine": 2.00,
        "methionine": 0.70,
        "methionine_cystine": 4.50,
        "threonine": 4.50,
        "tryptophan": 0.60,
        "calcium": 0.20,
        "phosphorus": 0.50,
        "price_per_kg": 8000
    },
    
    # ========== ROUGHAGES - FRESH ==========
    "Rumput Gajah": {
        "category": "Roughage - Fresh",
        "dry_matter": 20.0,
        "crude_protein": 10.0,
        "crude_fiber": 34.0,
        "ether_extract": 2.0,
        "ash": 12.0,
        "nfe": 42.0,
        "tdn": 55.0,
        "de_ruminant": 2.42,
        "me_ruminant": 1.99,
        "ne_lactation": 1.37,
        "ne_maintenance": 1.49,
        "ne_gain": 0.97,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.45,
        "methionine": 0.15,
        "methionine_cystine": 0.30,
        "threonine": 0.40,
        "tryptophan": 0.12,
        "calcium": 0.40,
        "phosphorus": 0.30,
        "price_per_kg": 500
    },
    "Rumput Raja": {
        "category": "Roughage - Fresh",
        "dry_matter": 18.0,
        "crude_protein": 11.0,
        "crude_fiber": 32.0,
        "ether_extract": 2.5,
        "ash": 11.0,
        "nfe": 43.5,
        "tdn": 56.0,
        "de_ruminant": 2.47,
        "me_ruminant": 2.02,
        "ne_lactation": 1.39,
        "ne_maintenance": 1.52,
        "ne_gain": 0.99,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.50,
        "methionine": 0.16,
        "methionine_cystine": 0.32,
        "threonine": 0.42,
        "tryptophan": 0.13,
        "calcium": 0.45,
        "phosphorus": 0.32,
        "price_per_kg": 600
    },
    "Rumput Lapang": {
        "category": "Roughage - Fresh",
        "dry_matter": 25.0,
        "crude_protein": 8.0,
        "crude_fiber": 30.0,
        "ether_extract": 2.0,
        "ash": 10.0,
        "nfe": 50.0,
        "tdn": 52.0,
        "de_ruminant": 2.29,
        "me_ruminant": 1.88,
        "ne_lactation": 1.29,
        "ne_maintenance": 1.41,
        "ne_gain": 0.91,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.35,
        "methionine": 0.12,
        "methionine_cystine": 0.24,
        "threonine": 0.32,
        "tryptophan": 0.10,
        "calcium": 0.35,
        "phosphorus": 0.25,
        "price_per_kg": 300
    },
    
    # ========== ROUGHAGES - DRY ==========
    "Jerami Padi": {
        "category": "Roughage - Dry",
        "dry_matter": 90.0,
        "crude_protein": 4.0,
        "crude_fiber": 35.0,
        "ether_extract": 1.5,
        "ash": 15.0,
        "nfe": 34.5,
        "tdn": 45.0,
        "de_ruminant": 1.98,
        "me_ruminant": 1.62,
        "ne_lactation": 1.12,
        "ne_maintenance": 1.22,
        "ne_gain": 0.79,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.15,
        "methionine": 0.08,
        "methionine_cystine": 0.16,
        "threonine": 0.14,
        "tryptophan": 0.05,
        "calcium": 0.40,
        "phosphorus": 0.10,
        "price_per_kg": 1500
    },
    "Jerami Jagung": {
        "category": "Roughage - Dry",
        "dry_matter": 88.0,
        "crude_protein": 5.5,
        "crude_fiber": 32.0,
        "ether_extract": 2.0,
        "ash": 8.0,
        "nfe": 40.5,
        "tdn": 50.0,
        "de_ruminant": 2.20,
        "me_ruminant": 1.81,
        "ne_lactation": 1.24,
        "ne_maintenance": 1.35,
        "ne_gain": 0.88,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.20,
        "methionine": 0.10,
        "methionine_cystine": 0.20,
        "threonine": 0.18,
        "tryptophan": 0.06,
        "calcium": 0.35,
        "phosphorus": 0.15,
        "price_per_kg": 1800
    },
    "Hay Alfalfa": {
        "category": "Roughage - Dry",
        "dry_matter": 90.0,
        "crude_protein": 18.0,
        "crude_fiber": 28.0,
        "ether_extract": 2.5,
        "ash": 9.0,
        "nfe": 32.5,
        "tdn": 58.0,
        "de_ruminant": 2.55,
        "me_ruminant": 2.09,
        "ne_lactation": 1.44,
        "ne_maintenance": 1.57,
        "ne_gain": 1.02,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.85,
        "methionine": 0.25,
        "methionine_cystine": 0.50,
        "threonine": 0.70,
        "tryptophan": 0.25,
        "calcium": 1.50,
        "phosphorus": 0.25,
        "price_per_kg": 8000
    },
    
    # ========== SILAGE ==========
    "Silase Jagung": {
        "category": "Roughage - Silage",
        "dry_matter": 30.0,
        "crude_protein": 8.0,
        "crude_fiber": 25.0,
        "ether_extract": 3.0,
        "ash": 5.0,
        "nfe": 49.0,
        "tdn": 65.0,
        "de_ruminant": 2.86,
        "me_ruminant": 2.35,
        "ne_lactation": 1.61,
        "ne_maintenance": 1.76,
        "ne_gain": 1.14,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.30,
        "methionine": 0.12,
        "methionine_cystine": 0.24,
        "threonine": 0.28,
        "tryptophan": 0.08,
        "calcium": 0.25,
        "phosphorus": 0.20,
        "price_per_kg": 1200
    },
    
    # ========== MINERALS ==========
    "Kapur (CaCO3)": {
        "category": "Mineral",
        "dry_matter": 99.0,
        "crude_protein": 0.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.0,
        "ash": 99.0,
        "nfe": 0.0,
        "tdn": 0.0,
        "de_ruminant": 0.0,
        "me_ruminant": 0.0,
        "ne_lactation": 0.0,
        "ne_maintenance": 0.0,
        "ne_gain": 0.0,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.0,
        "methionine": 0.0,
        "methionine_cystine": 0.0,
        "threonine": 0.0,
        "tryptophan": 0.0,
        "calcium": 38.0,
        "phosphorus": 0.0,
        "price_per_kg": 1500
    },
    "DCP (Dicalcium Phosphate)": {
        "category": "Mineral",
        "dry_matter": 99.0,
        "crude_protein": 0.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.0,
        "ash": 99.0,
        "nfe": 0.0,
        "tdn": 0.0,
        "de_ruminant": 0.0,
        "me_ruminant": 0.0,
        "ne_lactation": 0.0,
        "ne_maintenance": 0.0,
        "ne_gain": 0.0,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.0,
        "methionine": 0.0,
        "methionine_cystine": 0.0,
        "threonine": 0.0,
        "tryptophan": 0.0,
        "calcium": 24.0,
        "phosphorus": 18.5,
        "price_per_kg": 8000
    },
    "Garam (NaCl)": {
        "category": "Mineral",
        "dry_matter": 99.0,
        "crude_protein": 0.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.0,
        "ash": 99.0,
        "nfe": 0.0,
        "tdn": 0.0,
        "de_ruminant": 0.0,
        "me_ruminant": 0.0,
        "ne_lactation": 0.0,
        "ne_maintenance": 0.0,
        "ne_gain": 0.0,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.0,
        "methionine": 0.0,
        "methionine_cystine": 0.0,
        "threonine": 0.0,
        "tryptophan": 0.0,
        "calcium": 0.0,
        "phosphorus": 0.0,
        "price_per_kg": 3000
    },
    
    # ========== SYNTHETIC AMINO ACIDS ==========
    "DL-Methionine": {
        "category": "Amino Acid",
        "dry_matter": 99.0,
        "crude_protein": 58.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.0,
        "ash": 0.0,
        "nfe": 0.0,
        "tdn": 0.0,
        "de_ruminant": 0.0,
        "me_ruminant": 0.0,
        "ne_lactation": 0.0,
        "ne_maintenance": 0.0,
        "ne_gain": 0.0,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.0,
        "methionine": 99.0,
        "methionine_cystine": 99.0,
        "threonine": 0.0,
        "tryptophan": 0.0,
        "calcium": 0.0,
        "phosphorus": 0.0,
        "price_per_kg": 80000
    },
    "L-Lysine HCl": {
        "category": "Amino Acid",
        "dry_matter": 99.0,
        "crude_protein": 78.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.0,
        "ash": 0.0,
        "nfe": 0.0,
        "tdn": 0.0,
        "de_ruminant": 0.0,
        "me_ruminant": 0.0,
        "ne_lactation": 0.0,
        "ne_maintenance": 0.0,
        "ne_gain": 0.0,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 78.0,
        "methionine": 0.0,
        "methionine_cystine": 0.0,
        "threonine": 0.0,
        "tryptophan": 0.0,
        "calcium": 0.0,
        "phosphorus": 0.0,
        "price_per_kg": 75000
    },
    "L-Threonine": {
        "category": "Amino Acid",
        "dry_matter": 99.0,
        "crude_protein": 74.0,
        "crude_fiber": 0.0,
        "ether_extract": 0.0,
        "ash": 0.0,
        "nfe": 0.0,
        "tdn": 0.0,
        "de_ruminant": 0.0,
        "me_ruminant": 0.0,
        "ne_lactation": 0.0,
        "ne_maintenance": 0.0,
        "ne_gain": 0.0,
        "de_poultry": 0.0,
        "me_poultry": 0.0,
        "lysine": 0.0,
        "methionine": 0.0,
        "methionine_cystine": 0.0,
        "threonine": 98.0,
        "tryptophan": 0.0,
        "calcium": 0.0,
        "phosphorus": 0.0,
        "price_per_kg": 85000
    }
}

# Total: 40+ ingredients (can be expanded to 100+)

# ==========================================
# 🔍 FEED DATABASE FUNCTIONS
# ==========================================

def get_feed_by_category(category: str):
    """Get all feeds in a specific category"""
    return {name: data for name, data in FEED_DATABASE.items() 
            if data['category'].startswith(category)}

def search_feeds(query: str):
    """Search feeds by name"""
    query_lower = query.lower()
    return {name: data for name, data in FEED_DATABASE.items() 
            if query_lower in name.lower()}

def get_all_categories():
    """Get list of all feed categories"""
    categories = set()
    for data in FEED_DATABASE.values():
        # Extract main category (before hyphen)
        main_cat = data['category'].split(' - ')[0] if ' - ' in data['category'] else data['category']
        categories.add(main_cat)
    return sorted(list(categories))

def compare_feeds(feed_names: list, nutrients: list):
    """Compare nutritional content of multiple feeds"""
    comparison = {}
    for feed_name in feed_names:
        if feed_name in FEED_DATABASE:
            comparison[feed_name] = {
                nutrient: FEED_DATABASE[feed_name].get(nutrient, 0)
                for nutrient in nutrients
            }
    return comparison
